# Generated by Django 3.1.3 on 2020-11-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_api', '0002_auto_20201112_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='zoo_api.shelter'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='zoo_api.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='zoo_api.shelter'),
        ),
    ]
