# Generated by Django 3.1.3 on 2020-11-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_api', '0003_auto_20201112_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='linked_staff_date',
            field=models.DateTimeField(null=True),
        ),
    ]
