# Generated by Django 3.1.3 on 2020-11-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_api', '0006_auto_20201114_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='staff',
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='AnimalConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_date', models.DateField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_api.animal')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_api.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='animals',
            field=models.ManyToManyField(through='zoo_api.AnimalConnection', to='zoo_api.Animal'),
        ),
    ]
