# Generated by Django 3.1.3 on 2020-11-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_api', '0007_auto_20201117_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='linked_staff_date',
        ),
    ]
