# Generated by Django 3.1.3 on 2020-11-17 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_api', '0008_remove_animal_linked_staff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalconnection',
            name='connection_date',
            field=models.DateTimeField(default=datetime.date(2020, 11, 17)),
        ),
    ]
