# Generated by Django 3.1.3 on 2020-11-17 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_api', '0009_auto_20201117_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalconnection',
            name='connection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
